baseURL = "https://www.techstoa.com/"
languageCode = "en-us"
title = "Tech Stoa"
theme = "hugo-material-blog"
googleAnalytics = ""

[params]
    description = "Humanity Focused Technology and Philosophy"
    profilePic="techstoa.png"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]


[[menu.main]]
  name = "Home"
  weight = 10
  url = "/"

[[menu.main]]
  name = "Privacy Focus"
  weight = 20
  url = "/privacy"

[[menu.main]]
  name = "Social Lite App"
  weight = 30
  url = "/social-lite"

[[menu.main]]
  name = "Services"
  weight = 40
  url = "/services"

[[menu.main]]
  name = "Devices"
  weight = 50
  url = "/devices"

[[menu.main]]
  name = "Open Source"
  weight = 60
  url = "/open-source"

[[menu.main]]
  name = "About Us"
  weight = 80
  url = "/about-us"

[[menu.icon]]
    url = "mailto:gregory@auburndaletech.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/auburndale/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/techstoa/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/gregoryboyce/"
    name = "linkedin"
    weight = 4
