baseURL = "https://www.techstoa.com"
languageCode = "en-us"
title = "Tech Stoa: Humanity Focused Technology and Philosophy"
theme = "hugo-apps"
googleAnalytics = ""
author = "Gregory Boyce"
info = "Life Hacker"
tag = "mobile android friendica"

[params]
  googleAutoAds = ""
  avatar = "/techstoa.png"

[[menu.main]]
  name = "Home"
  weight = 10
  url = "/"

[[menu.main]]
  name = "Mobile Apps"
  weight = 20
  url = "/mobile-apps"

[[menu.main]]
  name = "Services"
  weight = 30
  url = "/services"

[[menu.main]]
  name = "Devices"
  weight = 40
  url = "/devices"

[[menu.main]]
  name = "Privacy Focus"
  weight = 50
  url = "/privacy"

[[menu.main]]
  name = "Contact Us"
  weight = 60
  url = "/contact"

