baseURL = "https://www.social-lite.app"
languageCode = "en-us"
title = "Social-Lite: Your Community Without Propaganda Tools"
theme = "hugo-apps"
googleAnalytics = ""
author = "Gregory Boyce"
info = "Life Hacker"
tag = "mobile android friendica"

[params]
  googleAutoAds = ""
  avatar = "/techstoa.png"

[[menu.main]]
  name = "Home"
  weight = 1
  url = "/"

[[menu.main]]
  name = "Mobile App"
  weight = 2
  url = "/mobile-app"

[[menu.main]]
  name = "Services"
  weight = 3
  url = "/services"

[[menu.main]]
  name = "Pod Hosting"
  weight = 4
  url = "/pod-hosting"

[[menu.main]]
  name = "Self-Hosting"
  weight = 5
  url = "/self-hosting"

[[menu.main]]
  name = "Contact Us"
  weight = 6
  url = "/contact"

