baseURL = "https://www.techstoa.com/"
languageCode = "en-us"
title = "Tech Stoa"
theme = "minimal"
Copyright = "© 2020 Auburndale Technology, LLC"
googleAnalytics = ""
paginate = 3
paginatePath = "page"

[params]
    description = "Humanity Focused Technology and Philosophy"
    profilePic="techstoa.png"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]


  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 10

  [[languages.en.menu.main]]
    url = "/privacy"
    name = "Privacy Focus"
    weight = 20

  [[languages.en.menu.main]]
    url = "/social-lite"
    name = "Social Lite App"
    weight = 30

  [[languages.en.menu.main]]
    url = "/services"
    name = "Services"
    weight = 40

  [[languages.en.menu.main]]
    url = "/devices"
    name = "Devices"
    weight = 50

  [[languages.en.menu.main]]
    url = "/open-source"
    name = "Open Source"
    weight = 60

  [[languages.en.menu.main]]
    url = "/about-techstoa"
    name = "About Tech Stoa"
    weight = 70
