baseURL = "https://www.social-lite.app"
languageCode = "en-us"
title = "Social-Lite: Your Community Without Propaganda Tools"
theme = "hugo-apps"
googleAnalytics = ""
author = "Gregory Boyce"
info = "Life Hacker"
tag = "mobile android friendica"

[params]
  googleAutoAds = ""
  avatar = "/techstoa.png"

[[menu.main]]
  name = "Home"
  weight = 10
  url = "/"

[[menu.main]]
  name = "Mobile App"
  weight = 20
  url = "/mobile-app"

[[menu.main]]
  name = "Services"
  weight = 30
  url = "/services"

[[menu.main]]
  name = "Devices"
  weight = 40
  url = "/devices"

[[menu.main]]
  name = "Contact Us"
  weight = 50
  url = "/contact"

