baseURL = "https://www.techstoa.com/"
languageCode = "en-us"
title = "Tech Stoa"
theme = "minimal"
Copyright = "© 2020 Auburndale Technology, LLC"
googleAnalytics = ""
paginate = 3
paginatePath = "page"

[params]
    description = "Humanity Focused Technology and Philosophy"
    favicon = "/favicon-32x32.ico"
    profilePic="techstoa.png"
    githubUsername = "#"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    hubspot = "8371071"

  [[menu.main]]
    url = "/"
    name = "Home"
    weight = 10

  [[menu.main]]
    url = "/essays"
    name = "Essays"
    weight = 15

  [[menu.main]]
    url = "/privacy"
    name = "Privacy Focus"
    weight = 20

  [[menu.main]]
    url = "/social-lite"
    name = "Social Lite App"
    weight = 30

  [[menu.main]]
    url = "/services"
    name = "Services"
    weight = 40

  [[menu.main]]
    url = "/devices"
    name = "Devices"
    weight = 50

  [[menu.main]]
    url = "/open-source"
    name = "Open Source"
    weight = 60

  [[menu.main]]
    url = "/philosophy"
    name = "Philosophy"
    weight = 65

  [[menu.main]]
    url = "/about-techstoa"
    name = "About Tech Stoa"
    weight = 70

  [[menu.icon]]
    url = "https://medium.com/tech-stoa"
    name = "medium"
    weight = 10

  [[menu.icon]]
    url = "mailto:gregory@auburndaletech.com"
    name = "envelope-o"
    weight = 20

  [[menu.icon]]
    url = "https://github.com/auburndale/"
    name = "github"
    weight = 30

  [[menu.icon]]
    url = "https://twitter.com/techstoa/"
    name = "twitter"
    weight = 40

  [[menu.icon]]
    url = "https://www.linkedin.com/in/gregoryboyce/"
    name = "linkedin"
    weight = 50
