version: "2"
services:

  haproxy:
    image: m21lab/haproxy:1.6.2
    links:
    - letsencrypt
    - techstoa
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
    - letsencrypt

  letsencrypt:
    image: m21lab/letsencrypt:1.0
    environment:
    - DOMAINS=www.techstoa.com
    - EMAIL=gregory@auburndaletech.com
    - LOAD_BALANCER_SERVICE_NAME=haproxy
    # THIS IS CRUCIAL WHEN TESTING to avoid reaching
    # the 5 certificates limit per domain per week.
    # You'll end up waiting a week before being able
    # to regenerate a valid cert if you don't backup
    # the once generated
    - OPTIONS=--staging
 
  techstoa: 
    image: nginx:latest
    container_name: techstoa
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - content:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=www.techstoa.com,localhost

  build:
    image: klakegg/hugo:0.74.3
    volumes:
      - ".:/src"
      - content:/src/public

volumes:
  content:
