version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  techstoa: 
    image: techstoa/website
    container_name: techstoa
    environment:
      - VIRTUAL_HOST=www.techstoa.com,techstoa.com,localhost

  staging:
    image: auburndale/techstoa:staging
    container_name: staging
    environment:
      - VIRTUAL_HOST=staging.techstoa.com

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
