version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  techstoa: 
    image: auburndale/techstoa
    container_name: techstoa
    environment:
      - VIRTUAL_HOST=www.techstoa.com,staging.techstoa.com,techstoa.com,localhost

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
