version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: techstoa
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    ports:
      - 8080:80
