version: '3'
services:

  # Keep images updated
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

  # Frontend Proxy
  frontend:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  production: 
    image: auburndale/techstoa
    container_name: techstoa
    environment:
      - VIRTUAL_HOST=www.techstoa.com,techstoa.com

  staging:
    image: auburndale/techstoa:staging
    container_name: staging
    environment:
      - VIRTUAL_HOST=staging.techstoa.com
