version: '3'
services:

  # Keep images updated
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

  # Frontend Proxy
  frontend:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  production: 
    image: auburndale/techstoa
    container_name: techstoa
    environment:
      - VIRTUAL_HOST=www.techstoa.com,techstoa.com

  staging:
    image: auburndale/techstoa:staging
    container_name: staging
    environment:
      - VIRTUAL_HOST=staging.techstoa.com

  analytics:
    image: plausible/analytics
    depends_on:
      - plausible_db
      - plausible_events_db
    links:
      - plausible_db
      - plausible_events_db
    env_file:
      - plausible-variables.env
    environment:
      - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
      - VIRTUAL_HOST=analytics.techstoa.com
      - VIRTUAL_PORT=8080

  plausible_db:
    image: postgres:12
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=plausible_db
      - POSTGRES_USER=postgres

  plausible_events_db:
    image: yandex/clickhouse-server:latest
    volumes:
      - event-data:/var/lib/clickhouse
    ports:
    - 8123:8123

  setup:
    image: plausible/analytics
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin"
    depends_on:
      - plausible_db
      - plausible_events_db
    links:
      - plausible_db
      - plausible_events_db
    env_file:
       - plausible-variables.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
